[web]
cloud-1-987-web-vm-01 private_ip=10.0.2.2

[db]
cloud-1-987-db-vm-01 private_ip=10.0.1.2

[all:vars]
ansible_user=dren
ansible_ssh_private_key_file=~/.ssh/id_rsa
lb_public_ip=34.54.49.97
    
[web:vars]
ansible_ssh_common_args='-o ProxyCommand="gcloud compute start-iap-tunnel %h %p --listen-on-stdin --project=cloud-1-987 --zone=europe-west8-b"'

[db:vars]
ansible_ssh_common_args='-o ProxyCommand="gcloud compute start-iap-tunnel %h %p --listen-on-stdin --project=cloud-1-987 --zone=europe-west8-a"'
