[web]
34.148.227.230

[db]
10.142.0.3

[all:vars]
ansible_user=dren
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
			
[db:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=dren@34.148.227.230'

